-d D:\project\gaowinwork\shizhong_demo\impl\gwsynthesis\shizhong_demo.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\project\gaowinwork\shizhong_demo\src\shizhong_demo.cst
-cfg D:\project\gaowinwork\shizhong_demo\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
