print(("ord(c)=", ord("c")))
print(("ord(d)=", ord("d")))
print("'c'>'d':", "c" > "d")
print("ord(‘输’)=", ord("输"))
print("ord(‘赢’)=", ord("赢"))
print("'输'>'赢':", "输" > "赢")
print("ord(‘中’)=", ord("中"))
print("ord(‘z’)=", ord("z"))
print("'中'>'z':", "中" > "z")
print(("ord(A)=", ord("A")))