screen=get (0,'Screensize');
W=screen(3);H=screen(4);
figure('Position',[0.2*H,0.2*H,0.5*W,0.3*H],...
'Name','图形演示系统','NumberTitle','off','MenuBar','none');
%定义P1ot菜单项
hplot = uimenu(gcf, 'Label', '&Plot');
uimenu(hplot, 'Label', 'Sine Wave', 'Callback', ...
    ['t = -pi:pi/20:pi;', 'plot(t, sin(t));', ...
    'set(hgon, ''Enable'', ''on'');', ...
    'set(hgoff, ''Enable'', ''on'');', ...
    'set(hbon, ''Enable'', ''on'');', ...
    'set(hboff, ''Enable'', ''on'');']);

uimenu(hplot, 'Label', 'Cosine Wave', 'Callback', ...
    ['t = -pi:pi/20:pi;', 'plot(t, cos(t));', ...
    'set(hgon, ''Enable'', ''on'');', ...
    'set(hgoff, ''Enable'', ''on'');', ...
    'set(hbon, ''Enable'', ''on'');', ...
    'set(hboff, ''Enable'', ''on'');']);

uimenu(hplot,'Label','Exit','Callback','close(gcf)');
