-d D:\Experiments\GOWIN\Examples\pwm_demo\impl\gwsynthesis\pwm_demo.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\Experiments\GOWIN\Examples\pwm_demo\src\pwm_demo.cst
-cfg D:\Experiments\GOWIN\Examples\pwm_demo\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
